version: 2.1

executors:
  compiler:
    docker:
      - image: docker:17.06.0-ce-git
    working_directory: ~/repo

jobs:
  cmake:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/cmake cmake
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/cmake; \
            else docker tag ataber/cmake ataber/cmake:${CIRCLE_BRANCH} && \
                 docker push ataber/cmake:${CIRCLE_BRANCH}; fi

  intel_mkl:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/intel_mkl intel_mkl
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/intel_mkl; \
            else docker tag ataber/intel_mkl ataber/intel_mkl:${CIRCLE_BRANCH} && \
                 docker push ataber/intel_mkl:${CIRCLE_BRANCH}; fi

  vtk:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/vtk vtk
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/vtk; \
            else docker tag ataber/vtk ataber/vtk:${CIRCLE_BRANCH} && \
                 docker push ataber/vtk:${CIRCLE_BRANCH}; fi

  mkl_vtk:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/mkl_vtk mkl_vtk
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/mkl_vtk; \
            else docker tag ataber/mkl_vtk ataber/mkl_vtk:${CIRCLE_BRANCH} && \
                 docker push ataber/mkl_vtk:${CIRCLE_BRANCH}; fi

  petsc:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/petsc petsc
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/petsc; \
            else docker tag ataber/petsc ataber/petsc:${CIRCLE_BRANCH} && \
                 docker push ataber/petsc:${CIRCLE_BRANCH}; fi

  slepc:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/slepc slepc
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/slepc; \
            else docker tag ataber/slepc ataber/slepc:${CIRCLE_BRANCH} && \
                 docker push ataber/slepc:${CIRCLE_BRANCH}; fi

  libmesh:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/libmesh libmesh
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/libmesh; \
            else docker tag ataber/libmesh ataber/libmesh:${CIRCLE_BRANCH} && \
                 docker push ataber/libmesh:${CIRCLE_BRANCH}; fi

  mfem:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/mfem mfem
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/mfem; \
            else docker tag ataber/mfem ataber/mfem:${CIRCLE_BRANCH} && \
                 docker push ataber/mfem:${CIRCLE_BRANCH}; fi

  trilinos:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/trilinos trilinos
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/trilinos; \
            else docker tag ataber/trilinos ataber/trilinos:${CIRCLE_BRANCH} && \
                 docker push ataber/trilinos:${CIRCLE_BRANCH}; fi

  dealii:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: docker build -t ataber/dealii dealii
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            if [[ ${CIRCLE_BRANCH} == "master" ]]; \
            then docker push ataber/dealii; \
            else docker tag ataber/dealii ataber/dealii:${CIRCLE_BRANCH} && \
                 docker push ataber/dealii:${CIRCLE_BRANCH}; fi

workflows:
  version: 2
  build-images:
    jobs:
      - cmake
      - vtk:
          requires:
            - cmake
      - intel_mkl:
          requires:
            - cmake
      - mkl_vtk:
          requires:
            - vtk
      - petsc:
          requires:
            - vtk
      - slepc:
          requires:
            - petsc
      - libmesh:
          requires:
            - slepc
      - mfem:
          requires:
            - slepc
      - trilinos:
          requires:
            - slepc
      - dealii:
          requires:
            - trilinos
